version: "2.3"
services:
  robotsf-cuda:
    image: robotsf-cuda
    build:
      context: .
    runtime: nvidia
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./model:/app/model
      - ./logs:/app/logs
      - ./scripts:/app/scripts
