version: "2.3"
services:
  robotsf-cuda:
    image: robotsf-cuda
    build:
      context: .
    runtime: nvidia
    volumes:
      - './profiles:/app/profiles'
    command: --cli --html --outfile /app/profiles/profile.html
