title = "Pedestrian Simulator Parameter config"

[map_files]
path_to_map_0 = "generated_map_10.json"
path_to_map_1 = "generated_map_11.json"
path_to_map_2 = "generated_map_12.json"
path_to_map_3 = "generated_map_13.json"
path_to_map_4 = "generated_map_14.json"
path_to_map_5 = "generated_map_15.json"
path_to_map_6 = "generated_map_16.json"
path_to_map_7 = "generated_map_17.json"
path_to_map_8 = "generated_map_18.json"
path_to_map_9 = "generated_map_19.json"
path_to_map_10 = "generated_map_20.json"
path_to_map_11 = "generated_map_21.json"
path_to_map_12 = "generated_map_22.json"
path_to_map_13 = "generated_map_23.json"
path_to_map_14 = "generated_map_24.json"
path_to_map_15 = "generated_map_25.json"
path_to_map_16 = "generated_map_26.json"
path_to_map_17 = "generated_map_27.json"
path_to_map_18 = "generated_map_6.json"
path_to_map_19 = "generated_map_7.json"
path_to_map_20 = "generated_map_8.json"
path_to_map_21 = "generated_map_9.json"

[info]
number_of_maps = 22
created = "2021-02-16 13:44:18"
author = "DESKTOP-MC8AIKN"

[simulator.generation]
actions = [ "standalone_individual", "group", "both", "none",]
probabilities = [ 20, 20, 10, 50,]

[simulator.group_actions]
actions = [ "split", "merge", "group_standalone", "none",]
probabilities = [ 5, 1, 9, 85,]

[simulator.stopping]
actions = [ "stop_pedestrian", "stop_group", "move_pedestrian", "move_group", "none",]
probabilities = [ 10, 10, 10, 10, 60,]

[simulator.flags]
allow_dynamic_grouping = true
allow_max_steps_stop = true
rendezvous_centroid = true
topology_operations_on_stopped = true
topology_operations_on_unfreezing = true
random_map = true
random_initial_population = true
random_initial_groups = false
default_map = false
update_peds = true

[simulator.default]
box_size = 20
ped_sparsity = 15
states = [ [ 0.0, 10.0, -0.5, -0.5, 0.0, -25.0,], [ 0.5, 10.0, -0.5, -0.5, 0.5, -25.0,], [ 4.0, 0.0, 0.0, 0.5, 1.0, 25.0,], [ 5.0, 0.0, 0.0, 0.5, 2.0, 25.0,], [ 6.0, 0.0, 0.0, 0.5, 25.0, 6.0,], [ 3.0, 0.0, 0.0, 0.5, 25.0, 7.0,],]
groups = [ [], [], [ 1, 0,], [], [ 2, 3,], [], [],]

[simulator.custom]
map_number = 6
ped_sparsity = 15

[simulator.generation.parameters]
max_single_peds = 3
max_group_size = 7
group_width_max = 6
group_width_min = 2.5
average_speed = 0.5

[simulator.group_actions.parameters]
max_standalone_grouping = 5

[simulator.stopping.parameters]
max_nsteps_ped_stopped = 100
max_nsteps_group_stopped = 100
max_stopping_pedestrians = 5
max_unfreezing_pedestrians = 5

[simulator.pedestrian.parameters]
max_stopping_groups = 1
max_number_pedestrian_stop = 5
max_unfreezing_pedestrians = 5

[simulator.default.obstacles]
obstacle1 = [ [ -1.0, 1.0, -1.0, -1.0,], [ 1.0, 1.0, -1.0, 2.5,], [ 1.0, -1.0, 2.5, 2.5,], [ -1.0, -1.0, 2.5, -1.0,],]
obstacle2 = [ [ -7, -5, -7, -7,], [ -7, -7, -7, -3,], [ -7, -5, -3, -7,],]

[simulator.custom.random_population]
max_initial_peds = [0, 2, 5, 10, 15, 20]
max_initial_groups = 7
max_peds_per_group = 3
